from logging.config import fileConfig
from pathlib import Path
import os
import sys

from dotenv import load_dotenv
from sqlalchemy import engine_from_config, pool
from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

BASE_DIR = Path(__file__).resolve().parents[1]
sys.path.append(str(BASE_DIR))

load_dotenv(BASE_DIR / ".env")

from database import Base, normalize_database_url  # noqa: E402
import models  # noqa: F401,E402
import subscriber_models  # noqa: F401,E402
import market_models  # noqa: F401,E402

target_metadata = Base.metadata

# These constraints already exist in every deployed schema, but are deliberately
# not represented as ORM relationships. SQLite also reflects the CHECK constraints
# generated by SQLAlchemy Enum differently from their in-memory representation.
# Ignore only those known legacy reflection mismatches; all tables, columns,
# indexes, named business constraints, and the market snapshot schema remain part
# of Alembic's normal comparison.
LEGACY_REFLECTED_ENUM_CONSTRAINTS = {
    "access_fulfillment_status",
    "audit_actor_type",
    "entitlement_access_status",
    "integration_processing_status",
    "integration_provider",
    "portal_access_token_purpose",
    "signal_delivery_attempt_outcome",
    "signal_publication_status",
    "subscriber_billing_status",
    "subscriber_signal_direction",
    "subscriber_signal_status",
    "subscription_event_source",
    "telegram_membership_status",
}
LEGACY_MIGRATION_ONLY_ADMIN_FOREIGN_KEYS = {
    ("access_entitlements", "revoked_by_admin_user_id", "users.id"),
    ("audit_events", "actor_admin_user_id", "users.id"),
    ("subscriber_signals", "approved_by_admin_user_id", "users.id"),
    ("subscriber_signals", "cancelled_by_admin_user_id", "users.id"),
    ("subscriber_signals", "created_by_admin_user_id", "users.id"),
}


def include_schema_object(obj, name, type_, reflected, compare_to):
    if not reflected or compare_to is not None:
        return True
    if type_ == "check_constraint" and name in LEGACY_REFLECTED_ENUM_CONSTRAINTS:
        return False
    if type_ == "foreign_key_constraint" and len(obj.elements) == 1:
        element = obj.elements[0]
        identity = (
            obj.table.name,
            element.parent.name,
            element.target_fullname,
        )
        if identity in LEGACY_MIGRATION_ONLY_ADMIN_FOREIGN_KEYS:
            return False
    return True

database_url = os.getenv("DATABASE_URL")

if not database_url:
    raise ValueError("DATABASE_URL is not set. Check backend/.env")

database_url = normalize_database_url(database_url)
config.set_main_option("sqlalchemy.url", database_url)


def run_migrations_offline() -> None:
    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_schema_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section)

    if configuration is None:
        raise ValueError("Alembic configuration section is missing")

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_schema_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
