"""initial schema

Revision ID: 29f6de39d824
Revises: 
Create Date: 2026-05-08 17:00:47.411432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f6de39d824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m1_position', sa.String(), nullable=True),
    sa.Column('m1_silver_days', sa.Integer(), nullable=True),
    sa.Column('m2_position', sa.String(), nullable=True),
    sa.Column('m2_platinum_days', sa.Integer(), nullable=True),
    sa.Column('m3_position', sa.String(), nullable=True),
    sa.Column('m3_palladium_days', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_cycle_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_bot_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('users_checked', sa.Integer(), nullable=True),
    sa.Column('users_skipped', sa.Integer(), nullable=True),
    sa.Column('signals_detected', sa.Integer(), nullable=True),
    sa.Column('executed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_bot_reports_run_date'), 'daily_bot_reports', ['run_date'], unique=False)
    op.create_table('signal_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('au_ag', sa.Float(), nullable=True),
    sa.Column('au_pt', sa.Float(), nullable=True),
    sa.Column('au_pd', sa.Float(), nullable=True),
    sa.Column('silver_days', sa.Integer(), nullable=True),
    sa.Column('platinum_days', sa.Integer(), nullable=True),
    sa.Column('palladium_days', sa.Integer(), nullable=True),
    sa.Column('signal_fired', sa.Boolean(), nullable=True),
    sa.Column('signal_target', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('membership_level', sa.Enum('classic', 'founder', 'aurum', name='membershiplevel'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('preferred_trading_provider', sa.Enum('disabled', 'snaptrade', 'ibkr_fa', name='tradingprovider'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('broker_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('snaptrade_user_id', sa.String(), nullable=True),
    sa.Column('snaptrade_account_id', sa.String(), nullable=True),
    sa.Column('snaptrade_user_secret', sa.String(), nullable=True),
    sa.Column('can_display_portfolio', sa.Boolean(), nullable=False),
    sa.Column('can_execute_trades', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connecting', 'syncing', 'active', 'failed', 'disconnected', name='connectionstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_connections_snaptrade_user_id'), 'broker_connections', ['snaptrade_user_id'], unique=True)
    op.create_table('fa_authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending_authorization', 'active', 'rejected', 'revoked', 'suspended', name='faauthorizationstatus'), nullable=False),
    sa.Column('advisor_master_account_id', sa.String(), nullable=True),
    sa.Column('ibkr_client_account_id', sa.String(), nullable=True),
    sa.Column('authorization_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fa_authorizations_ibkr_client_account_id'), 'fa_authorizations', ['ibkr_client_account_id'], unique=False)
    op.create_index(op.f('ix_fa_authorizations_status'), 'fa_authorizations', ['status'], unique=False)
    op.create_index(op.f('ix_fa_authorizations_user_id'), 'fa_authorizations', ['user_id'], unique=True)
    op.create_table('ibkr_account_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('advisor_master_account_id', sa.String(), nullable=False),
    sa.Column('ibkr_client_account_id', sa.String(), nullable=False),
    sa.Column('account_alias', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibkr_account_mappings_advisor_master_account_id'), 'ibkr_account_mappings', ['advisor_master_account_id'], unique=False)
    op.create_index(op.f('ix_ibkr_account_mappings_ibkr_client_account_id'), 'ibkr_account_mappings', ['ibkr_client_account_id'], unique=True)
    op.create_index(op.f('ix_ibkr_account_mappings_user_id'), 'ibkr_account_mappings', ['user_id'], unique=True)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value_chf', sa.Float(), nullable=True),
    sa.Column('metal_held', sa.String(), nullable=True),
    sa.Column('gold_oz_equiv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'past_due', 'cancelled', name='subscriptionstatus'), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('disabled', 'snaptrade', 'ibkr_fa', name='tradingprovider'), nullable=True),
    sa.Column('from_metal', sa.String(), nullable=True),
    sa.Column('to_metal', sa.String(), nullable=True),
    sa.Column('ratio_col', sa.String(), nullable=True),
    sa.Column('ratio_value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('sell_order_id', sa.String(), nullable=True),
    sa.Column('buy_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'partial', name='tradestatus'), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bot_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('m1_enabled', sa.Boolean(), nullable=False),
    sa.Column('m1_position', sa.String(), nullable=True),
    sa.Column('m1_silver_days', sa.Integer(), nullable=True),
    sa.Column('m1_status', sa.Enum('ok', 'pending_switch', 'cash_pending_retry', 'cash_manual_review', 'paused', name='modulestatus'), nullable=True),
    sa.Column('m1_error_message', sa.String(), nullable=True),
    sa.Column('m1_retry_count', sa.Integer(), nullable=True),
    sa.Column('m1_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('m1_last_status_change', sa.DateTime(), nullable=True),
    sa.Column('m1_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('m1_last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('m2_enabled', sa.Boolean(), nullable=False),
    sa.Column('m2_position', sa.String(), nullable=True),
    sa.Column('m2_platinum_days', sa.Integer(), nullable=True),
    sa.Column('m2_status', sa.Enum('ok', 'pending_switch', 'cash_pending_retry', 'cash_manual_review', 'paused', name='modulestatus'), nullable=True),
    sa.Column('m2_error_message', sa.String(), nullable=True),
    sa.Column('m2_retry_count', sa.Integer(), nullable=True),
    sa.Column('m2_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('m2_last_status_change', sa.DateTime(), nullable=True),
    sa.Column('m2_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('m2_last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('m3_enabled', sa.Boolean(), nullable=False),
    sa.Column('m3_position', sa.String(), nullable=True),
    sa.Column('m3_palladium_days', sa.Integer(), nullable=True),
    sa.Column('m3_status', sa.Enum('ok', 'pending_switch', 'cash_pending_retry', 'cash_manual_review', 'paused', name='modulestatus'), nullable=True),
    sa.Column('m3_error_message', sa.String(), nullable=True),
    sa.Column('m3_retry_count', sa.Integer(), nullable=True),
    sa.Column('m3_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('m3_last_status_change', sa.DateTime(), nullable=True),
    sa.Column('m3_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('m3_last_trade_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bot_states_user_id'), 'user_bot_states', ['user_id'], unique=True)
    op.create_table('user_module_positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('metal', sa.String(), nullable=False),
    sa.Column('etf_symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('last_value_chf', sa.Float(), nullable=False),
    sa.Column('last_fill_price', sa.Float(), nullable=True),
    sa.Column('last_sell_order_id', sa.String(), nullable=True),
    sa.Column('last_buy_order_id', sa.String(), nullable=True),
    sa.Column('last_execution_log_id', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_name', name='uq_user_module_position')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('disabled', 'snaptrade', 'ibkr_fa', name='tradingprovider'), nullable=False),
    sa.Column('fa_authorization_id', sa.String(), nullable=True),
    sa.Column('ibkr_account_mapping_id', sa.String(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('from_metal', sa.String(), nullable=True),
    sa.Column('to_metal', sa.String(), nullable=True),
    sa.Column('ratio_col', sa.String(), nullable=True),
    sa.Column('ratio_value', sa.Float(), nullable=True),
    sa.Column('target_value_chf', sa.Float(), nullable=True),
    sa.Column('estimated_value_chf', sa.Float(), nullable=True),
    sa.Column('from_quantity', sa.Float(), nullable=True),
    sa.Column('to_quantity', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('sell_order_id', sa.String(), nullable=True),
    sa.Column('buy_order_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'skipped', 'success', 'failed', name='executionstatus'), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fa_authorization_id'], ['fa_authorizations.id'], ),
    sa.ForeignKeyConstraint(['ibkr_account_mapping_id'], ['ibkr_account_mappings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_idempotency_key'), 'execution_logs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_execution_logs_user_id'), 'execution_logs', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('broker_connection_id', sa.String(), nullable=False),
    sa.Column('metal', sa.String(), nullable=True),
    sa.Column('etf_symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('last_price_gbp', sa.Float(), nullable=True),
    sa.Column('value_chf', sa.Float(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_index(op.f('ix_execution_logs_user_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_idempotency_key'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_table('user_module_positions')
    op.drop_index(op.f('ix_user_bot_states_user_id'), table_name='user_bot_states')
    op.drop_table('user_bot_states')
    op.drop_table('trade_log')
    op.drop_table('subscriptions')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_ibkr_account_mappings_user_id'), table_name='ibkr_account_mappings')
    op.drop_index(op.f('ix_ibkr_account_mappings_ibkr_client_account_id'), table_name='ibkr_account_mappings')
    op.drop_index(op.f('ix_ibkr_account_mappings_advisor_master_account_id'), table_name='ibkr_account_mappings')
    op.drop_table('ibkr_account_mappings')
    op.drop_index(op.f('ix_fa_authorizations_user_id'), table_name='fa_authorizations')
    op.drop_index(op.f('ix_fa_authorizations_status'), table_name='fa_authorizations')
    op.drop_index(op.f('ix_fa_authorizations_ibkr_client_account_id'), table_name='fa_authorizations')
    op.drop_table('fa_authorizations')
    op.drop_index(op.f('ix_broker_connections_snaptrade_user_id'), table_name='broker_connections')
    op.drop_table('broker_connections')
    op.drop_table('users')
    op.drop_table('signal_log')
    op.drop_index(op.f('ix_daily_bot_reports_run_date'), table_name='daily_bot_reports')
    op.drop_table('daily_bot_reports')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
